/* ============================================================
   audio.js - every sound in this game is generated by maths.

   There are no .mp3 or .wav files anywhere. The browser's Web Audio
   API lets us build tones from scratch, so the whole soundtrack costs
   zero download and can never hit a copyright problem.

   The music uses Mayamalavagowla, a very old South Indian raga - that
   is the scale that makes it sound Tamil rather than generic fantasy.
   ============================================================ */
(function () {
  var A = {
    ctx: null,
    master: null,
    musicGain: null,
    sfxGain: null,
    muted: false,
    ready: false
  };

  // Semitone steps of the notes we are allowed to use.
  var RAGA_MAYAMALAVAGOWLA = [0, 1, 4, 5, 7, 8, 11, 12];  // solemn, ancient, a little tense
  var RAGA_MOHANAM         = [0, 2, 4, 7, 9, 12, 14, 16]; // bright and happy - used for the ending

  // Turn "note number in the scale" into an actual frequency in Hz.
  function noteHz(scale, degree, octave, root) {
    var n = scale[((degree % scale.length) + scale.length) % scale.length];
    var extra = Math.floor(degree / scale.length) * 12;
    return (root || 146.83) * Math.pow(2, (n + extra + (octave || 0) * 12) / 12);
  }

  /* The audio engine is only allowed to start after the player has
     touched or clicked something - every browser insists on this. */
  A.start = function () {
    if (A.ctx) { if (A.ctx.state === 'suspended') A.ctx.resume(); return; }
    var Ctx = window.AudioContext || window.webkitAudioContext;
    if (!Ctx) return;
    A.ctx = new Ctx();

    A.master = A.ctx.createGain();
    A.master.gain.value = A.muted ? 0 : 0.9;
    A.master.connect(A.ctx.destination);

    A.musicGain = A.ctx.createGain();
    A.musicGain.gain.value = 0.34;
    A.musicGain.connect(A.master);

    A.sfxGain = A.ctx.createGain();
    A.sfxGain.gain.value = 0.55;
    A.sfxGain.connect(A.master);

    A.ready = true;
  };

  A.setMuted = function (m) {
    A.muted = m;
    if (A.master) A.master.gain.setTargetAtTime(m ? 0 : 0.9, A.ctx.currentTime, 0.05);
  };

  /* ---------- tiny building blocks ---------- */

  // one plain tone with a volume envelope
  function tone(opts) {
    if (!A.ready) return;
    var t = A.ctx.currentTime + (opts.delay || 0);
    var osc = A.ctx.createOscillator();
    var g = A.ctx.createGain();
    osc.type = opts.type || 'sine';
    osc.frequency.setValueAtTime(opts.f0, t);
    if (opts.f1) osc.frequency.exponentialRampToValueAtTime(Math.max(20, opts.f1), t + opts.dur);

    var peak = opts.gain === undefined ? 0.3 : opts.gain;
    g.gain.setValueAtTime(0.0001, t);
    g.gain.exponentialRampToValueAtTime(peak, t + (opts.attack || 0.005));
    g.gain.exponentialRampToValueAtTime(0.0001, t + opts.dur);

    var out = g;
    if (opts.filter) {
      var f = A.ctx.createBiquadFilter();
      f.type = opts.filter;
      f.frequency.value = opts.cutoff || 1200;
      f.Q.value = opts.q || 1;
      g.connect(f); out = f;
    }
    osc.connect(g);
    out.connect(opts.bus || A.sfxGain);
    osc.start(t);
    osc.stop(t + opts.dur + 0.05);
  }

  // a burst of hiss - used for sand, cloth, breaking wood, cymbals
  function noise(opts) {
    if (!A.ready) return;
    var t = A.ctx.currentTime + (opts.delay || 0);
    var len = Math.max(0.02, opts.dur);
    var buf = A.ctx.createBuffer(1, Math.ceil(A.ctx.sampleRate * len), A.ctx.sampleRate);
    var d = buf.getChannelData(0);
    for (var i = 0; i < d.length; i++) d[i] = Math.random() * 2 - 1;

    var src = A.ctx.createBufferSource();
    src.buffer = buf;

    var f = A.ctx.createBiquadFilter();
    f.type = opts.filter || 'bandpass';
    f.frequency.setValueAtTime(opts.cutoff || 1400, t);
    if (opts.cutoff1) f.frequency.exponentialRampToValueAtTime(opts.cutoff1, t + len);
    f.Q.value = opts.q || 1;

    var g = A.ctx.createGain();
    g.gain.setValueAtTime(opts.gain === undefined ? 0.3 : opts.gain, t);
    g.gain.exponentialRampToValueAtTime(0.0001, t + len);

    src.connect(f); f.connect(g); g.connect(opts.bus || A.sfxGain);
    src.start(t); src.stop(t + len + 0.02);
  }

  /* A cartoon voice. Two "formant" filters on a buzzy tone is roughly how
     a human vowel is shaped, so this reads as a shouted word rather than a beep. */
  var VOWELS = { a: [730, 1090], o: [570, 840], i: [270, 2290], e: [530, 1840], u: [300, 870] };

  function say(syllables, baseHz, opts) {
    if (!A.ready) return;
    opts = opts || {};
    var time = A.ctx.currentTime + (opts.delay || 0);
    for (var i = 0; i < syllables.length; i++) {
      var syl = syllables[i];
      var form = VOWELS[syl.v] || VOWELS.a;
      var dur = syl.d || 0.16;

      var osc = A.ctx.createOscillator();
      osc.type = 'sawtooth';
      osc.frequency.setValueAtTime(baseHz * (syl.p || 1), time);
      osc.frequency.linearRampToValueAtTime(baseHz * (syl.p2 || syl.p || 1), time + dur);

      var g = A.ctx.createGain();
      var vol = 0.5 * (opts.gain || 1);
      g.gain.setValueAtTime(0.0001, time);
      g.gain.exponentialRampToValueAtTime(vol, time + 0.03);
      g.gain.setValueAtTime(vol, time + dur * 0.6);
      g.gain.exponentialRampToValueAtTime(0.0001, time + dur);

      var f1 = A.ctx.createBiquadFilter();
      f1.type = 'bandpass'; f1.frequency.value = form[0]; f1.Q.value = 6;
      var f2 = A.ctx.createBiquadFilter();
      f2.type = 'bandpass'; f2.frequency.value = form[1]; f2.Q.value = 8;

      var mix = A.ctx.createGain(); mix.gain.value = 0.9;
      osc.connect(g);
      g.connect(f1); g.connect(f2);
      f1.connect(mix); f2.connect(mix);
      mix.connect(A.sfxGain);

      osc.start(time); osc.stop(time + dur + 0.03);
      time += dur * 0.92;
    }
  }

  /* ---------- sound effects ---------- */
  A.sfx = {
    jump:     function () { tone({ type: 'triangle', f0: 300, f1: 520, dur: 0.12, gain: 0.16 }); },
    land:     function () { noise({ cutoff: 320, cutoff1: 120, dur: 0.09, gain: 0.22, filter: 'lowpass' }); },
    step:     function () { noise({ cutoff: 900, dur: 0.045, gain: 0.05 }); },
    swing:    function () { noise({ cutoff: 2600, cutoff1: 700, dur: 0.14, gain: 0.2, q: 0.8 }); },
    clang:    function () { tone({ type: 'square', f0: 1750, f1: 900, dur: 0.22, gain: 0.16, filter: 'bandpass', cutoff: 2400, q: 4 });
                            noise({ cutoff: 3200, dur: 0.18, gain: 0.12 }); },
    hitFlesh: function () { tone({ type: 'sine', f0: 180, f1: 60, dur: 0.16, gain: 0.3 });
                            noise({ cutoff: 700, dur: 0.1, gain: 0.18, filter: 'lowpass' }); },
    barrel:   function () { noise({ cutoff: 1500, cutoff1: 260, dur: 0.3, gain: 0.32, filter: 'lowpass' });
                            tone({ type: 'square', f0: 220, f1: 70, dur: 0.2, gain: 0.12 }); },
    spike:    function () { tone({ type: 'sawtooth', f0: 900, f1: 200, dur: 0.13, gain: 0.14, filter: 'lowpass', cutoff: 1800 }); },
    gate:     function () { tone({ type: 'sawtooth', f0: 90, f1: 150, dur: 0.7, gain: 0.14, filter: 'lowpass', cutoff: 500 });
                            noise({ cutoff: 400, dur: 0.7, gain: 0.1, filter: 'lowpass' }); },
    lever:    function () { tone({ type: 'square', f0: 520, f1: 320, dur: 0.1, gain: 0.14 }); },
    pickup:   function () { tone({ type: 'triangle', f0: 660, dur: 0.1, gain: 0.2 });
                            tone({ type: 'triangle', f0: 990, dur: 0.16, gain: 0.18, delay: 0.08 }); },
    heart:    function () { tone({ type: 'sine', f0: 520, dur: 0.12, gain: 0.2 });
                            tone({ type: 'sine', f0: 780, dur: 0.2, gain: 0.16, delay: 0.1 }); },
    hurt:     function () { say([{ v: 'a', d: 0.14, p: 1.15, p2: 0.9 }], 210, { gain: 0.8 });
                            tone({ type: 'sawtooth', f0: 260, f1: 120, dur: 0.14, gain: 0.1 }); },
    // "Ayyo!" - what you shout in Tamil when things go wrong.
    ayyo:     function () { say([{ v: 'a', d: 0.16, p: 1.25, p2: 1.1 }, { v: 'o', d: 0.34, p: 1.0, p2: 0.55 }], 200, { gain: 1 }); },
    // A guard spotting you - "Yaar angae?!" (who is there?!)
    alert:    function () { say([{ v: 'a', d: 0.13, p: 0.95, p2: 1.15 }, { v: 'a', d: 0.12, p: 1.2 }, { v: 'e', d: 0.2, p: 1.35, p2: 1.5 }], 150, { gain: 0.9 }); },
    guardDie: function () { say([{ v: 'u', d: 0.2, p: 1.0, p2: 0.4 }], 140, { gain: 0.8 }); },
    roar:     function () { say([{ v: 'o', d: 0.5, p: 0.55, p2: 0.35 }], 90, { gain: 1.2 });
                            noise({ cutoff: 220, dur: 0.6, gain: 0.2, filter: 'lowpass' }); },
    slam:     function () { tone({ type: 'sine', f0: 120, f1: 35, dur: 0.4, gain: 0.5 });
                            noise({ cutoff: 260, dur: 0.35, gain: 0.3, filter: 'lowpass' }); },
    page:     function () { noise({ cutoff: 2400, cutoff1: 900, dur: 0.16, gain: 0.12 }); },
    menu:     function () { tone({ type: 'triangle', f0: 440, dur: 0.07, gain: 0.15 }); },
    cheer:    function () { for (var i = 0; i < 7; i++) noise({ cutoff: 900 + Math.random() * 1400, dur: 0.5, gain: 0.06, delay: i * 0.06 }); }
  };

  /* ---------- the music sequencer ----------
     Every frame we look a fraction of a second into the future and book
     the notes that are about to happen. That keeps the rhythm rock steady
     even if the drawing stutters. */
  var music = {
    on: false,
    name: null,
    pending: null,
    track: null,
    step: 0,
    nextAt: 0,
    tempo: 0.5,
    drone: null,
    droneGain: null
  };

  // Each track: which scale, how fast, what the drums do, and the melody line.
  var TRACKS = {
    intro:   { scale: RAGA_MAYAMALAVAGOWLA, root: 130.81, tempo: 0.42, mel: [0, 2, 1, 0, -1, 0, 2, 3, 2, 1, 0, -2, 0, 1, 0, -1], drums: 0.22, lead: 0.16 },
    menu:    { scale: RAGA_MAYAMALAVAGOWLA, root: 146.83, tempo: 0.46, mel: [0, 2, 1, 4, 2, 1, 0, -1, 0, 2, 4, 3, 2, 1, 0, 0], drums: 0.12, lead: 0.13 },
    level1:  { scale: RAGA_MAYAMALAVAGOWLA, root: 146.83, tempo: 0.38, mel: [0, 2, 4, 2, 3, 1, 0, 2, 4, 5, 4, 2, 1, 0, -1, 0], drums: 0.30, lead: 0.14 },
    level2:  { scale: RAGA_MAYAMALAVAGOWLA, root: 146.83, tempo: 0.30, mel: [0, 4, 3, 4, 5, 4, 2, 4, 6, 5, 4, 2, 3, 1, 0, 2], drums: 0.42, lead: 0.16 },
    level3:  { scale: RAGA_MAYAMALAVAGOWLA, root: 130.81, tempo: 0.23, mel: [0, 1, 4, 1, 5, 4, 1, 0, 3, 4, 6, 4, 3, 1, 0, -1], drums: 0.55, lead: 0.20 },
    boss:    { scale: RAGA_MAYAMALAVAGOWLA, root: 110.00, tempo: 0.19, mel: [0, 0, 1, 0, 4, 3, 1, 0, 0, 1, 5, 4, 3, 1, 0, 0], drums: 0.70, lead: 0.22 },
    victory: { scale: RAGA_MOHANAM, root: 174.61, tempo: 0.26, mel: [0, 1, 2, 3, 4, 3, 2, 4, 5, 4, 3, 2, 1, 2, 3, 4], drums: 0.50, lead: 0.20 }
  };

  function startDrone(root) {
    stopDrone();
    if (!A.ready) return;
    var g = A.ctx.createGain();
    g.gain.value = 0.0001;
    g.gain.setTargetAtTime(0.09, A.ctx.currentTime, 0.6);

    var lp = A.ctx.createBiquadFilter();
    lp.type = 'lowpass'; lp.frequency.value = 700;

    var oscs = [];
    // the tanpura idea: the root note, the fifth above it, and the octave
    var parts = [[root / 2, 1], [root * 1.4983, 0.55], [root, 0.5]];
    for (var i = 0; i < parts.length; i++) {
      var o = A.ctx.createOscillator();
      o.type = 'sawtooth';
      o.frequency.value = parts[i][0];
      o.detune.value = Math.random() * 8 - 4;
      var og = A.ctx.createGain();
      og.gain.value = 0.12 * parts[i][1];
      o.connect(og); og.connect(lp);
      o.start();
      oscs.push(o);
    }
    lp.connect(g); g.connect(A.musicGain);
    music.drone = oscs; music.droneGain = g;
  }

  function stopDrone() {
    if (!music.drone) return;
    var list = music.drone;
    music.droneGain.gain.setTargetAtTime(0.0001, A.ctx.currentTime, 0.25);
    setTimeout(function () {
      for (var i = 0; i < list.length; i++) { try { list[i].stop(); } catch (e) {} }
    }, 900);
    music.drone = null; music.droneGain = null;
  }

  // mridangam-ish drum: "tha" is a pitched thump, "ki" is a dry tick
  function drumTha(at, vol) {
    var o = A.ctx.createOscillator(), g = A.ctx.createGain();
    o.type = 'sine';
    o.frequency.setValueAtTime(190, at);
    o.frequency.exponentialRampToValueAtTime(70, at + 0.16);
    g.gain.setValueAtTime(vol, at);
    g.gain.exponentialRampToValueAtTime(0.0001, at + 0.2);
    o.connect(g); g.connect(A.musicGain);
    o.start(at); o.stop(at + 0.24);
  }

  function drumKi(at, vol) {
    var len = 0.06;
    var buf = A.ctx.createBuffer(1, Math.ceil(A.ctx.sampleRate * len), A.ctx.sampleRate);
    var d = buf.getChannelData(0);
    for (var i = 0; i < d.length; i++) d[i] = (Math.random() * 2 - 1) * (1 - i / d.length);
    var src = A.ctx.createBufferSource(); src.buffer = buf;
    var f = A.ctx.createBiquadFilter(); f.type = 'bandpass'; f.frequency.value = 2600; f.Q.value = 2;
    var g = A.ctx.createGain(); g.gain.value = vol;
    src.connect(f); f.connect(g); g.connect(A.musicGain);
    src.start(at); src.stop(at + len);
  }

  // plucked string, standing in for a veena
  function pluck(at, hz, vol, dur) {
    var o = A.ctx.createOscillator(), g = A.ctx.createGain(), f = A.ctx.createBiquadFilter();
    o.type = 'sawtooth';
    o.frequency.setValueAtTime(hz, at);
    f.type = 'lowpass';
    f.frequency.setValueAtTime(hz * 6, at);
    f.frequency.exponentialRampToValueAtTime(hz * 1.4, at + dur);
    f.Q.value = 2;
    g.gain.setValueAtTime(0.0001, at);
    g.gain.exponentialRampToValueAtTime(vol, at + 0.012);
    g.gain.exponentialRampToValueAtTime(0.0001, at + dur);
    o.connect(f); f.connect(g); g.connect(A.musicGain);
    o.start(at); o.stop(at + dur + 0.05);
  }

  A.playMusic = function (name) {
    if (!A.ready) { music.pending = name; return; }
    if (music.on && music.name === name) return;
    var tr = TRACKS[name];
    if (!tr) return;
    music.name = name;
    music.track = tr;
    music.on = true;
    music.step = 0;
    music.tempo = tr.tempo;
    music.nextAt = A.ctx.currentTime + 0.1;
    startDrone(tr.root);
  };

  A.stopMusic = function () {
    music.on = false; music.name = null; music.pending = null;
    if (A.ready) stopDrone();
  };

  // called every frame from the game loop
  A.update = function () {
    if (!A.ready) return;
    if (music.pending) { var p = music.pending; music.pending = null; A.playMusic(p); }
    if (!music.on) return;

    var tr = music.track;
    var lookahead = A.ctx.currentTime + 0.2;
    var guard = 0;
    while (music.nextAt < lookahead && guard++ < 32) {
      var at = music.nextAt;
      var s = music.step % 16;

      // drums: strong beat every 4 steps, dry ticks in between
      if (s % 4 === 0) drumTha(at, tr.drums * (s === 0 ? 1 : 0.7));
      if (s % 2 === 1) drumKi(at, tr.drums * 0.3);
      if (tr.drums > 0.4 && s % 8 === 6) drumTha(at, tr.drums * 0.5);

      // melody
      var deg = tr.mel[s];
      if (deg !== undefined && deg !== null) {
        pluck(at, noteHz(tr.scale, deg, 0, tr.root) * 2, tr.lead, music.tempo * 2.2);
        if (s % 8 === 0) pluck(at, noteHz(tr.scale, deg, -1, tr.root), tr.lead * 0.7, music.tempo * 3);
      }

      music.nextAt += music.tempo;
      music.step++;
    }
  };

  CR.Audio = A;
})();
